apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao
  template:
    metadata: 
      labels: 
        app: conversao
    spec:
      containers:
        - name: conversao
          image: machado1976/conversao-temperatura:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  ports:
    - port: 8080
      protocol: TCP
      name: http
  type: LoadBalancer